// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace reverseEFCore.Models.Models;

public partial class CustomerCustomerDemo
{
    public string CustomerId { get; set; }

    public string CustomerTypeId { get; set; }

    public virtual Customer Customer { get; set; }
}