// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace reverseEFCore.Models.Models;

public partial class Employee
{
    public int EmployeeId { get; set; }

    public string LastName { get; set; }

    public string FirstName { get; set; }

    public string Title { get; set; }

    public string TitleOfCourtesy { get; set; }

    public DateTime? BirthDate { get; set; }

    public DateTime? HireDate { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string Region { get; set; }

    public string PostalCode { get; set; }

    public string Country { get; set; }

    public string HomePhone { get; set; }

    public string Extension { get; set; }

    public byte[] Photo { get; set; }

    public string Notes { get; set; }

    public int? ReportsTo { get; set; }

    public string PhotoPath { get; set; }

    public virtual ICollection<Employee> InverseReportsToNavigation { get; set; } = new List<Employee>();

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();

    public virtual Employee ReportsToNavigation { get; set; }
    /*
     *  Employee'nin Orders özelliğinin işlevi ne.
     *    1. Çalışanın aldığı tüm siparişleri görmek -> IEnumerable 
     *    2. çalışanın siparişlerine yeni bir sipariş eklemek -> ICollection 
     *    3. Çalışanın siparişlerinden 3. siparişe (emp.Orders[1] -> IList
     *    4. Çalışanın siparişlerine WHERE ya da Order by veya Group by gibi işlemler -> IQueryable
     *                                                                                -> List<>
    
     */
}